### ISSUE TITLE
Add `graph` command for locations

### ISSUE THREAD

**Issue by JacobEvelyn** [JacobEvelyn/friends#109]

**Comment by andypearson** [comment]
I've already hung out with `graph` a bit, so I'll take this!

**Comment by JacobEvelyn** [comment]
Sounds great! As always, let me know if you have any questions.

**Comment by JacobEvelyn** [comment]
@andypearson are you still interested in working on this? If not I might try to knock it off this week.

**Comment by andypearson** [comment]
I am, but life caught up with me. Feel free to do it first if you fancy, I'm not going to have time this week but should be back to pick a few things sometime soon!

**Comment by JacobEvelyn** [comment]
Cool, thanks! I may try to work on other features first to give you more time here then.

**Comment by JacobEvelyn** [comment]
This is no longer needed given #124.
