### ISSUE TITLE
Change #hashtags to @tags

### ISSUE THREAD

**Issue by JacobEvelyn** [JacobEvelyn/friends#122]
Would love thoughts on this. One problem with `#hashtags` is they're considered comments in most shells, which means users might try to use something like `friends list friends --tagged #school` instead of the correct `friends list friends --tagged school` or `friends list friends --tagged '#school'`. Another issue is that when #121 is done, you won't be able to add an activity all in the command line without quoting the whole thing, which is clearly against the spirit of #121.

`@tags` are also used by https://github.com/ginatrapani/todo.txt-cli

Curious what others think.

**Comment by andypearson** [comment]
To me `#tag` is additional meta data and `@tag` is a person. But I've been on Twitter since the early days :D

**Comment by JacobEvelyn** [comment]
Yeah I agree that `#tag` is a little more semantic given Twitter, but I keep getting frustrated by Zsh treating them as comments and not letting me use them without quoting everything.

**Comment by andypearson** [comment]
Is it weird to support both formats for input?

**Comment by JacobEvelyn** [comment]
Ha, I was thinking about that as well. Not too weird code-wise but I think if I saw that I'd wonder why there were two options instead of just one.

@andypearson would you be willing to take a look at the `email-tags` branch I wrote which changes tag behavior from `#tag` to `@tag` and automatically converts all tags in your `friends.md` file? I'd love to hear what you think after using it, especially now that you don't have to quote things anymore (so you can for instance just run `friends add activity yesterday: Went for a run with Dave. @exercise`

**Comment by andypearson** [comment]
Just started tagging some stuff, ran this:

```
friends graph --tagged #friday
Error: missing argument: --tagged
```

Had to change it to:

```
friends graph --tagged "#friday"
```

Which is terrible! I am 100% behind a switch to `@tags`! :D

**Comment by JacobEvelyn** [comment]
Hehe yep, that's exactly what converted me too :)

Will change soon.

**Comment by JacobEvelyn** [comment]
This is changed in v0.24, which just released. Note that the change auto-updates your old `#tags` into new `@tags` so no data will be lost.

**Comment by andypearson** [comment]
Auto-updating worked a treat. It's looking good!
