### ISSUE TITLE
Change `graph` to use `--with`, `--tagged`, and `--in` flags

### ISSUE THREAD

**Issue by JacobEvelyn** [JacobEvelyn/friends#124]

**Comment by andypearson** [comment]
I could have a look at this whilst I'm graphing locations...

**Comment by andypearson** [comment]
Having thought more (for a whopping 20 minutes), this is a much better way of allowing locations to be graphed, I think it supersedes #109 (which can probably be closed now).

**Comment by JacobEvelyn** [comment]
Yep, agreed. I'll assign this to you then!

**Comment by andypearson** [comment]
Cool! Working on it now...
