### ISSUE TITLE
Add integration tests for bin/friends?

### ISSUE THREAD

**Issue by JacobEvelyn** [JacobEvelyn/friends#127]
The code is pretty extensively unit-tested, but as @andypearson showed in #126, bugs can pop up in `bin/friends`. Integration tests could be helpful in preventing these sorts of errors in the future, but they could also not be worth the effort to maintain.

One related note I've been thinking about for the past few months is that since this codebase has effectively become a CLI and not a library used outside that purpose, maybe it makes sense to test everything _only_ via integration tests? The downside there is it might be nice to have these independent, well-tested classes in the future.

Would love to hear thoughts.

**Comment by andypearson** [comment]
Do you have any experience with https://github.com/cucumber/aruba?

**Comment by JacobEvelyn** [comment]
I don't but thanks for the link! Looks like a great place to start!

**Comment by JacobEvelyn** [comment]
I'm working on converting all tests over to integration tests (the unit tests feel kind of icky with all of the stubbing going on), using some simple homemade framework code to keep this clean.

**Comment by andypearson** [comment]
Awesome! I'll look forward to seeing how that looks. Good luck!

**Comment by JacobEvelyn** [comment]
@andypearson I just finished this after a bit of a hiatus. Feel free to take a look if you're interested. I'll be working soon on finishing up the last few open issues for a 1.0 release. 🎊

**Comment by andypearson** [comment]
@JacobEvelyn great stuff! I'm thinking of writing a command line app at some point so this will make an excellent reference :)

One thing I noticed; now that's you're targeting 2.4.0 in the `.ruby-version` you can switch to using the  [squiggly heredoc](https://ruby-doc.org/core-2.4.0/doc/syntax/literals_rdoc.html#label-Here+Documents) so things line up nicely:

```
      describe "when one name is contained within another via hyphens" do
        let(:description) { "Met Mary-Jo-Kate." }

        # Make sure "Jo" is a closer friend than "Mary-Jo-Kate" so we know our
        # test result isn't due to chance.
        let(:content) do
          <<~FILE
            ### Activities:
            - 2017-01-01: Singing with **Jo Stafford**.

            ### Friends:
            - Jo Stafford
            - Mary-Jo-Kate Olsen

            ### Locations:
          FILE
        end

        it { line_added "- #{date}: Met **Mary-Jo-Kate Olsen**." }
        it { stdout_only "Activity added: \"#{date}: Met Mary-Jo-Kate Olsen.\"" } if test_stdout
      end
```

And I'm still using `friends` to track my life, here are my current stats.

```
Total activities: 292
Total friends: 162
Total time elapsed: 397 days
```

Thanks again for making it :D

**Comment by JacobEvelyn** [comment]
@andypearson Thanks for the tip about squiggly heredocs—I didn't know that was a feature. I don't think I can make that change yet though as `friends` still supports all the way back to Ruby 2.1.0—see [`.travis.yml`](https://github.com/JacobEvelyn/friends/blob/master/.travis.yml). (The `.ruby-version` is really just to get my [`chruby`](https://github.com/postmodern/chruby) setup working and I should probably add that to the `.gitignore`.) But definitely good to keep in mind for the future!

Re: the tests, I've been wondering if it would be worthwhile to extract the CLI-testing setup I did (basically just the functions in [`test/helper.rb`](https://github.com/JacobEvelyn/friends/blob/master/test/helper.rb)) into a new gem. Probably not useful right now but if you're working on a CLI program that could use it let me know. :)

Glad to hear you're still using it!
