### ISSUE TITLE
Error: stack level too deep

### ISSUE THREAD

**Issue by Andersos** [JacobEvelyn/friends#136]
VERSION -  0.24

I keep getting "Error: stack level too deep" on every command of this tool.

```bash
$ friends update
Error: stack level too deep
```

```bash
$ friends --debug update
/Users/anders/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/friends-0.24/lib/friends/serializable.rb:26:in `initialize_dup': stack level too deep (SystemStackError)
	from /Users/anders/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/friends-0.24/lib/friends/serializable.rb:26:in `merge'
	from /Users/anders/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/friends-0.24/lib/friends/serializable.rb:26:in `each'
	from /Users/anders/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/friends-0.24/lib/friends/serializable.rb:26:in `reduce'
	from /Users/anders/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/friends-0.24/lib/friends/serializable.rb:26:in `deserialize'
	from /Users/anders/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/friends-0.24/lib/friends/introvert.rb:610:in `parse_line!'
	from /Users/anders/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/friends-0.24/lib/friends/introvert.rb:570:in `block in read_file'
	from /Users/anders/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/friends-0.24/lib/friends/introvert.rb:566:in `foreach'
	from /Users/anders/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/friends-0.24/lib/friends/introvert.rb:566:in `with_index'
	 ... 10067 levels...
	from /Users/anders/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/gli-2.14.0/lib/gli/app_support.rb:82:in `run'
	from /Users/anders/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/friends-0.24/bin/friends:465:in `<top (required)>'
	from /Users/anders/.rbenv/versions/2.3.0/bin/friends:22:in `load'
	from /Users/anders/.rbenv/versions/2.3.0/bin/friends:22:in `<main>'
```

**Comment by JacobEvelyn** [comment]
Thanks for the bug report, @Andersos! I'll work on resolving this right away. Since I can't reproduce it, I'm wondering if your `friends.md` file has something formatted incorrectly (either from manual editing or due to a bug in the code) that's making it go into a recursive spiral. That's also consistent with you seeing errors on every command, since every command reads the file. (As a side note, you've made me realize that we don't need to read the file for `friends update` so I've created #137 to handle that.)

Would you be willing to paste the contents of your `friends.md` file here (or you can email it to me privately at jacobevelyn@gmail.com) so I can take a look at the formatting? I'd love to make this more resilient and give more helpful error messages but a file that reproduces this would be extremely helpful. Thanks!

(And if you don't want to share your file with me, you might have luck comparing its formatting to the sample `friends.md` file included in this repo to see where they differ.)

**Comment by Andersos** [comment]
Thanks for the answer. I wanted to test the tool. Following the Readme I ran `gem install friends` then started to use the commands. Right away from the beginning this error turned up. After reading more in the Readme I thought I needed to create a file so I ran the command `friends --filename ./friends.md`. That didn't make anything better so I ended up coming here creating this issue.

My `friends.md` file is empty or it contains:
```md
### Activities:

### Friends:

### Locations:

```

If there are any other way I can help debug this please let me know. Maybe it is related to how I have setup Ruby on my machine.

```bash
$ which ruby
/Users/anders/.rbenv/shims/ruby

$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

$ friends -v
friends version 0.24
```

The permissions of my friends file is the following `-rw-r--r--`

Wow, something strange happend when I was writing this answer. I deleted the friends file thinking it might change something and it did. Suddenly the commands started to work. The update command worked. I tried adding a friend it worked. And then suddenly again it broke. Now it is back to
```bash
$ friends update
Error: stack level too deep
```

Maybe this command output will help. I think not though:
```bash
$ rm friends.md 
$ friends update
Already up-to-date (0.24)
$ friends update
Already up-to-date (0.24)
$ friends update
Already up-to-date (0.24)
$ friends update
Already up-to-date (0.24)
$ friends update
Already up-to-date (0.24)
$ friends update
Already up-to-date (0.24)
$ friends update
Already up-to-date (0.24)
$ friends update
Already up-to-date (0.24)
$ friends list friend
$ friends list friend
$ friends list friend
$ friends list friend
$ friends list friends
$ friends list
Error: Command 'list' requires a subcommand friends,activities,locations,tags,favorite
$ friends update
Already up-to-date (0.24)
$ friends add friends "Anders Olsen Sandvik"
Error: Too many arguments for command
$ friends add friend "Anders Olsen Sandvik"
Friend added: "Anders Olsen Sandvik"
$ friends list friends
Error: stack level too deep
$ friends list
Error: stack level too deep
$ friends
NAME
    friends - Spend time with the people you care about. Introvert-tested. Extrovert-approved.

SYNOPSIS
    friends [global options] command [command options] [arguments...]

VERSION
    0.24

GLOBAL OPTIONS
    --debug             - Debug error messages with a full backtrace
    --filename=FILENAME - Set the location of the friends file (default: ./friends.md)
    --help              - Show this message
    --quiet             - Quiet output messages
    --version           - Display the program version

COMMANDS
    add     - Adds a friend (or nickname), activity, or location
    clean   - Cleans your friends.md file
    edit    - Opens the `friends.md` file in $EDITOR for manual editing
    graph   - Graph activities over time
    help    - Shows a list of commands or help for one command
    list    - Lists friends, activities, and locations
    remove  - Remove a nickname
    rename  - Renames a friend or location
    set     - Set data about friends
    stats   - List all stats
    suggest - Suggest friends to do activities with
    update  - Updates the `friends` program

$ friends list friends
Error: stack level too deep
```

**Comment by JacobEvelyn** [comment]
Thanks so much for the detailed review! I'm looking into this now.

**Comment by JacobEvelyn** [comment]
Ah, I found the issue. I had code that migrated tags from the old format (`#tag`) to the new format (`@tag`) that involved re-parsing the file, and if you didn't already have at least one friend and one activity then you'd end up in an infinite loop of parsing the file.

This is another vote in favor of basic integration tests à la #127.

**Comment by Andersos** [comment]
Wow, great. Thanks for having a look. I'm really glad we, read you, found these things. Luckily some of them were known already. I'm also glad you marked some of the issues with "upforgrabs" making it easy for new people, to the project, to help out. I was afraid to post the issue but you have been very friendly so thanks for being a good human ⭐ 

I'm looking forward to playing more with the tool you built 👍

**Comment by andypearson** [comment]
@JacobEvelyn I've stumbled here trying to reproduce another bug I think I've found (more on that later!)

I'm seeing the same thing that @Andersos is getting when running `bin/friends` on your `infinity` branch, so it looks like that doesn't quite sort the issue...

Let me know if I can be of assistance!

**Comment by JacobEvelyn** [comment]
@Andersos Thanks for your patience. I found a problem with my original approach so I just ended up removing the troublesome code as it was only used for migrating people on a previous version. I've just pushed a fix up (version 0.25)—please let me know if it works for you! I'll keep this issue open until I hear that things are resolved.

@andypearson I'd love to hear more about what bug you were investigating. Could you make a separate issue?

**Comment by andypearson** [comment]
Yup, I'll make a new ticket.

And false alarm, 0.25 seems to fix all of the stack level issues!

**Comment by Andersos** [comment]
Yey, 0.25 works for me now =)

**Comment by JacobEvelyn** [comment]
Good to hear! Thanks for all the help here!
