### ISSUE TITLE
Friends list should include tags and nicknames

### ISSUE THREAD

**Issue by andypearson** [JacobEvelyn/friends#161]
Friends allow tags and nicknames, but you can't (as far as I know) see them without looking in the friends.md file itself.

`friends list friends` should return nicknames and tags on the same line (for easy grepping).

The output should be colorised.

Maybe a table based format would be nice and readable.

**Comment by andypearson** [comment]
I don't know when it'd be, but I'd be quite keen to take this...

**Comment by JacobEvelyn** [comment]
@andypearson you can see this info with [`friends list friends --verbose`](https://github.com/JacobEvelyn/friends#list-friends). Do you think this should be the default behavior?

**Comment by andypearson** [comment]
Wow! Exactly what I was looking for.

As it seems that `friends list friends` is the only command that accepts `--verbose` I think it'd be reasonable to have it as the default behaviour.

I've added the flag to my alias anyway now, so I get it for free :)

**Comment by JacobEvelyn** [comment]
Closing this for now; will reopen if others would prefer this behavior switched.
