### ISSUE TITLE
Add notes

### ISSUE THREAD

**Issue by skorokithakis** [JacobEvelyn/friends#175]
Would it be possible/desirable to add notes for friends? Things like "John's mother got the flu" or "Mary's son started school", so we could query for those later on?

**Comment by JacobEvelyn** [comment]
Hmm, that's an interesting idea. I'm not sure I totally follow what you're describing though.

How are you picturing that behaving differently from just an activity?

**Comment by skorokithakis** [comment]
An activity is something I did with a friend. A note is something I want to remember about them so I can maybe follow up later. For example, if I went for drinks with a friend and we talked about various things, I might want to note that they broke up, or that they got a new job, or something like that.

**Comment by skorokithakis** [comment]
By the way, I should add that notes are friend-specific, so the section would look something like:

```markdown
### Notes:
- 2017-06-12, John Doe: Is getting married next September.
- 2017-06-10, John Doe: Is finishing his PhD.
- 2017-02-1, Jane Doe: Just got a job.
```

Then the cli could have a command like `friends list notes <friend name>` to get all the notes for a friend.

**Comment by JacobEvelyn** [comment]
Interesting! But I suspect it could also be useful to add notes for more than one friend, like:

```
### Notes:
- 2017-06-12: **John Doe** and **Jane Doe** just got engaged.
```

Does that seem right? My read is that they're basically just activities that I didn't participate in.

**Comment by skorokithakis** [comment]
Hmm, yes, possibly. I'm wondering whether they aren't activities in the sense that it's something that happened, e.g. is "John Doe has been feeling down after he lost his job" an activity? Although I guess "John Doe told me so-and-so" is an activity, I guess. Maybe you're right that they're just activities...

**Comment by skorokithakis** [comment]
Actually, the use case is that you can have easily-accessible, highly summarized details of what's going on in a person's life. This is mostly for stuff you want to follow up on, rather than for things that you did together, so if you stick it in activities you'd then have to wade through all the "went out with X in Y" lines to get to the "actionable" items.

**Comment by skorokithakis** [comment]
Also, are activities meant to be added multiple times per activity? Ie if you have four notes that happened in one outing (John Doe told me W, X, Y and Z), should that be four activities? Won't this skew the stats?

**Comment by JacobEvelyn** [comment]
Sorry for being unclear; I didn't mean to say that notes _were_ activities, but rather that they behave _like_ activities in that the way you're describing them they can be tied to any number of friends or locations. So I imagine much of the activity code could be repurposed if we were to treat them as such.

One question I have though is whether you see them as things that need a specific date tied to them or if it's more like a todo list: "I need to follow up with Susan," etc. Does that question make sense?

And as for your question about skewing stats, overall `friends` is meant to be very flexible—stats are what you want them to be! For example, I personally don't use tags but I know others do. So I think anything that makes sense to both of us is likely to be a good start in figuring out how notes could/should work.

**Comment by skorokithakis** [comment]
Oh, sorry, I see what you mean now. Yes, from a data model standpoint, notes are pretty much exactly activities, with the only difference being that you can filter them by friend in the cli and sort them by date.

I think the date is much more useful than not, as I see this feature as supplementing my memory, and not so much as a todo list (ie it's for the past instead of the future). So, if a friend asks if I remember one of their exes, I can quickly look at my notes and refresh my memory on who that person was (maybe tags would be helpful here).

**Comment by JacobEvelyn** [comment]
Makes sense, thanks. (Though I should point out that you _can_ filter activities by friend/date too: [`friends list activities --with Susan --after '2 weeks ago'`](https://github.com/JacobEvelyn/friends#list-activities))

I think this feature makes sense and seems useful to me! Would you be interested in taking a stab at an initial implementation? (I'm happy to provide lots of guidance.)

**Comment by skorokithakis** [comment]
Sure, I've never written a line of Ruby, but I can take a stab at it. I'll let you know if it's too foreign, thanks!

**Comment by skorokithakis** [comment]
Ugh, I'm stuck two seconds in... How do I get `./bin/friends` to pick up the changes from the `lib` dir, instead of the installed gem?

**Comment by skorokithakis** [comment]
Oh, sorry, I figured it out. I had to install something called `bundler`, but that's working now.

**Comment by JacobEvelyn** [comment]
Glad to hear it! Let me know if there's anything in [CONTRIBUTING.md](https://github.com/JacobEvelyn/friends/blob/master/CONTRIBUTING.md) that I can add to make it easier to get started.

**Comment by skorokithakis** [comment]
I was a bit confused by step 4, thinking that `bundle install && overcommit --install` would install the package locally, which would make it harder for me to change files. You may want to add a note that "this will install the dependencies".

**Comment by JacobEvelyn** [comment]
Thanks, will do. (And I _just_ removed the `overcommit` line, since that's now part of our CI test suite rather than something developers run locally.)

**Comment by JacobEvelyn** [comment]
Just made a change... is it clearer now or still confusing?

**Comment by skorokithakis** [comment]
Nope, crystal clear now, thanks!

**Comment by skorokithakis** [comment]
I've tried a bit and it seems learning Ruby would take much longer than implementing the feature, so I'm afraid I'll have to defer to someone more experienced :/

**Comment by JacobEvelyn** [comment]
No worries @skorokithakis; I appreciate you trying. I'm adding the `upforgrabs` label in case anyone wants to take this. @skorokithakis if you want to try again I'm happy to give you lots of guidance and walk you through what to change!

**Comment by JacobEvelyn** [comment]
@skorokithakis (and @ddddavidmartin and @mnocon) I'm hoping to devote more time to `friends` development and am wondering if this is still a feature you guys are interested in. I'm also curious about whether, six months later, any of you have insights into anything else that would make this feature (or `friends` in general) really nice to use. Thoughts?

**Comment by skorokithakis** [comment]
I've lately stopped using `friends` as much, I think mainly because it's lacking this feature. Tracking whom I spend time with is good, but not very actionable. Having notes so I don't forget what my friends are up to would be useful to me. Other than that, I find `friends` pretty easy to use, and don't have any more particular insight on how this feature could work.

Perhaps one thing I do miss would be a command to reparse the file and generating lists of friends/locations from the activities. I sometimes just go and edit the file directly, adding `_locations_` and `**friends**` by hand, and it would be nice if `friends` would realize those were missing from the lists and added them.

**Comment by JacobEvelyn** [comment]
@skorokithakis thanks! I've created #182 for us to discuss your file-reparsing suggestion. And I'm glad to hear notes would still be useful. The way I'm thinking about it now is something like this:

```
$ friends add note Marie just got married
Note added: "2018-01-04: Marie Curie just got married"
```

but allow notes to involve more than one friend, like activities:

```
$ friends add note Marie and Pierre just got married
Note added: "2018-01-04: Marie Curie and Pierre Curie just got married"
```

They'd be stored exactly the same as activities but in a new section:

```
### Notes:
- 2018-01-04: **Marie Curie** and **Pierre Curie** just got married
- 2017-06-12: **John Doe** is getting married next September.
- 2017-06-10: **John Doe** is finishing his PhD.
- 2017-02-1: **Jane Doe** just got a job.
```

Then you can search your notes exactly the same way you can search activities:

```
$ friends list notes --with John
2017-06-12: John Doe is getting married next September.
2017-06-10: John Doe is finishing his PhD.
```

Does that seem right? Is there anything you'd change, or anything I'm missing that would improve this?

**Comment by skorokithakis** [comment]
Yep, that seems exactly right! For my usage, it'd also be useful to delete notes (for when they're no longer relevant), but I can do that by hand. Notes are more of a "current" tool rather than a historical one, so they're for keeping track what's going on in someone's life right now rather than what happened overall. Maybe they could be both, though.

**Comment by JacobEvelyn** [comment]
Thanks! I kind of suspect that some users might want to see historical notes as well (like "oh right, this is when John was doing his PhD") though I guess that doesn't a delete command wouldn't be useful. For an initial implementation though I think it makes sense to not have a way to delete notes (after all, we currently can't delete friends or activities either) and if we find that it feels like it should be a command we can add it later.

How does that sound to you @skorokithakis?

**Comment by skorokithakis** [comment]
Yeah, definitely. I'm more interested in the search command also searching the text of the notes, deletion is easy enough to do manually.

**Comment by JacobEvelyn** [comment]
Ah, interesting. Full text search is a neat idea and should be pretty straightforward for a basic implementation. That's also something I've thought about adding to `list activities` as well but always figured people could just use `grep` instead for more flexibility, like `$ friends list activities --since 'January 1st 2018' | grep skiing`. (I can also add some `grep` examples to the README.)

Of course, it's nice to have that feature built-in, but `grep` provides lots of extra features like highlighting, regex matching, etc. that I wouldn't want to add in here. Do you think `grep` would work for notes too or is that too ugly?

**Comment by skorokithakis** [comment]
I think grep is a bit too much hassle, since I have to go into the directory where I keep the file and grep it. However, I'd only need grep-like functionality for `friends search` anyway (basically case-insensitive substring matching) so I could just alias `fr search` to `grep friends.md` if you think that command doesn't belong here.

It would be handy to be able to do `fr search notes PhD`, `fr search activities skiing`, things like that, though.

**Comment by JacobEvelyn** [comment]
I'm not sure you followed my `grep` suggestion—I'm not saying people should be calling `grep` on the actual `friends.md` file (which I agree would be a hassle) but rather just pipe the output of `friends list activities` or `friends list notes` into `grep`, like this:

```
$ friends list notes | grep PhD
2017-07-01: Marie Curie just got accepted into a PhD program.
2017-06-10: John Doe is finishing his PhD.
```

and you can combine this with the normal filter options provided by `friends`, like this:

```
$ friends list notes --with John | grep PhD
2017-06-10: John Doe is finishing his PhD.
```

Does that make sense?

**Comment by JacobEvelyn** [comment]
Cool, I'll add that to the README as well!

**Comment by mnocon** [comment]
My two cents: the notes feature is the one I'm missing the most and the examples you gave perfectly describe the way I'd use it. There's no need for a command deleting them, I can always do it manually.

Thank you for developing friends, it's an awesome tool 🙂

**Comment by JacobEvelyn** [comment]
Thanks @mnocon, that's super helpful! Unfortunately I'm both sick and traveling for the next few days but I'll get this feature out as soon as I can.

**Comment by JacobEvelyn** [comment]
@skorokithakis @mnocon @ddddavid this feature is now released in version 0.35. Let me know how you like it! (Also it was kind of a big change so if there are any subtle interactions with notes that I didn't think through properly, or documentation that I didn't update, please tell me!)

**Comment by mnocon** [comment]
@JacobEvelyn I've successfully upgraded and it works! Looks good so far, I'll be provide more feedback in the upcoming weeks.

**Comment by ddddavidmartin** [comment]
Thanks for the heads up @JacobEvelyn! I haven't been using friends, quite possibly for the lack of a notes feature. I tried out the latest version with notes support and I quite like it so far. It is different from what I was picturing, but better!

**Comment by JacobEvelyn** [comment]
Thanks for the feedback, @ddddavidmartin. I really appreciate it. I'd love to hear any other thoughts you have on why you stopped using `friends` or anything else you'd like it to support.
