### ISSUE TITLE
Parse friends.md and generate lists of friends/locations from the activities

### ISSUE THREAD

**Issue by JacobEvelyn** [JacobEvelyn/friends#182]
@skorokithakis in [this comment](https://github.com/JacobEvelyn/friends/issues/175#issuecomment-355269522) you say:

> Perhaps one thing I do miss would be a command to reparse the file and generating lists of friends/locations from the activities. I sometimes just go and edit the file directly, adding _locations_ and **friends** by hand, and it would be nice if friends would realize those were missing from the lists and added them.

I think I see what you're getting at but I'm not positive—could you explain this a little more?

**Comment by skorokithakis** [comment]
Basically, if you go into `friends.md` and add this line:

~~~
- 2017-09-27: Went to _Some new place_ with **New person 1** and **New person 2**.
~~~

the locations and friends lists won't be updated with the new people (as far as I know). It would be good if `friends edit` did some sanity checking and updating after `$EDITOR` had quit, or if there were a command to do this after the fact.

**Comment by JacobEvelyn** [comment]
Ooh interesting! Thanks for the clarification.

I think there's a few ways this could be implemented:

1. Do this automatically every time the file is written.
  - **Pros**:
    - We already do something similar (`friends clean` is called internally every time the file is written, which sorts the output within the file), so this would be fairly easy to implement.
    - This could actually become a nice feature. When you have a new friends (or new group of friends) you don't have to add them one-by-one first, you can instead just put them in asterisks the first time and they're added.
      - Note that this could probably only support adding new friend/location names, and not also giving them tags or giving friends locations or nicknames. (So you could do something like `$ friends add activity 'Hung out with **Marie Curie** in _Paris_.'` but if you tried to do `$ friends add activity 'Hung out with **Marie Curie** (a.k.a. MC) [Paris] @scientist in _Paris_.'` it wouldn't set the Marie's nickname, location, or tag as you might hope.
  - **Cons**:
    - If someone uses asterisks or underscores emphatically (like they add an activity with the text `Went to lunch with Marie and the food was **SO GOOD**!`) it would automatically add that string as a friend or location.
      - Note that we could detect these additions and print something so the output would look like:
```
$ friends add activity 'Went with Marie and Pierre to _Paris_ where we ate the most **amazing** escargots.'
Activity added: "2018-01-04: Went with Marie Curie and Pierre Curie to Paris.
Friend added: amazing
Location added: Paris
```
2. A standalone command (like `friends reparse`, or making this part of the existing `friends clean` command).
  - **Pros**:
    - We already have the `friends clean` command which does something similar. It wouldn't be hard to either change it or give it a flag like `--add-missing-friends` or `--add-missing-locations`.
  - **Cons**:
    - Has mostly the same "unexpected behavior" con as option 1, but slightly lessened because this is only being done when people explicitly run it so they expect it.
    - We don't get the auto-add benefit of option 1.
3. Have `friends edit` use something like [listen](https://github.com/guard/listen) or [filewatcher](https://github.com/thomasfl/filewatcher) to watch when the file is saved and perform the additions then.
  - **Pros**:
    - Only happens when the user is likely to intend it to happen, as anyone editing the `friends.md` file directly should be aware that asterisks and underscores have meaning.
  - **Cons**:
    - Would likely add significant complexity to `friends edit` as well as a large dependency.
    - We don't get the auto-add benefit of option 1.

Do these options match your thinking? Are there things about them that I'm not thinking through? Is there another approach you're imagining?

**Comment by skorokithakis** [comment]
No, this matches my thinking pretty much exactly. It seems a bit overcomplicated to me, as I'd just do:

~~~
def friends_edit():
    subprocess.open("$EDITOR friends.md")
    friends_clean()
~~~

I.e. I'd clean the file every time the editor closed and control returned to me, so I wouldn't have to mess with inotify or rewriting things from under the user's nose while they're editing.

In short, I'd make this a part of `friends clean` and *additionally* run it after the editor was closed. I see the problem with the asterisks, unfortunately I think the only solution there is to have people use single asterisks.

**Comment by JacobEvelyn** [comment]
Ah, that's really helpful. I hadn't thought about using a forked subprocess to open the editor and then cleaning up after that process is terminated. I'll look into how easy that is to do in Ruby.

**Comment by skorokithakis** [comment]
If it's anything like Python (and I don't see why it wouldn't be), it should be trivial. You can just use `Open3#popen3()`.

**Comment by JacobEvelyn** [comment]
Yeah, the tricky thing is that some editors (like Atom, Sublime Text 3, VS Code, etc.) have a standard command (like `atom`, `subl`, or `code`) to open the editor from the command line, and these commands themselves terminate before the editor does, so I think I need to wait for the process group to terminate rather than just that process.

**Comment by skorokithakis** [comment]
Ah, that's too bad. I don't think you need perfect with this, especially since people can just run `friends clean` afterwards. This is just a helper function, so I wouldn't worry too much about it to start with.

**Comment by JacobEvelyn** [comment]
Fortunately, I just discovered that `atom`, `subl`, and `code` all support a `--wait` flag that forces the command to not terminate until the files you opened are closed, for exactly this use case, so I can just note in the README that people should use that option when they set `EDITOR`.

**Comment by JacobEvelyn** [comment]
@skorokithakis this is implemented in v0.36! Let me know how it works for you!

**Comment by skorokithakis** [comment]
@JacobEvelyn Will do, just upgraded to test out the notes functionality as well, thanks!

**Comment by skorokithakis** [comment]
Yep, seems to work like a charm, it found my new locations and friends, thanks!

**Comment by JacobEvelyn** [comment]
Awesome, thanks for letting me know!
