### ISSUE TITLE
Allow (some) punctuation in tags

### ISSUE THREAD

**Issue by adiabatic** [JacobEvelyn/friends#186]
I wanted to tag an activity `@games:caverna`, but only the `@games` part was recognized as a tag. Does anyone oppose adding `:` and `-` to the regex on [line 6 of friends/lib/friends.rb](https://github.com/JacobEvelyn/friends/blob/9be02fc9161acbe0238d1bb19fa24d0a59ce33a9/lib/friends.rb#L6)?

**Comment by JacobEvelyn** [comment]
I think that seems reasonable to me, @adiabatic. Would you be interested in making a PR for that change?

**Comment by JacobEvelyn** [comment]
Just a bit more thinking here—it probably makes sense to allow some punctuation (like `:` and `-`) in the _middle_ of a tag, but not at the beginning or end in case someone is recording an activity like `@games: I played Caverna today`. Does that seem right to folks?

**Comment by adiabatic** [comment]
Sounds right to me.

As an aside, I'll definitely do the PR, most likely this week, but I've been busy with other things. Data entry seems to work fine for my current use cases, so I'm not in a rush.

**Comment by JacobEvelyn** [comment]
Sounds great! Let me know if you have any questions about how to make the change or add tests for it!
