### ISSUE TITLE
Generate Searchable Static Site

### ISSUE THREAD

**Issue by Immortalin** [JacobEvelyn/friends#209]
Like one of those fancy documentation tools e.g. docusaurus

**Comment by JacobEvelyn** [comment]
Hey @Immortalin, so sorry for the slow response. Can you share a little more about what you're thinking here? Are you looking for a searchable static site for the documentation? Or for your own `friends.md` data?

**Comment by JacobEvelyn** [comment]
I haven't heard back, so I'm closing this. Feel free to reopen if you want to chat more about this!
