### ISSUE TITLE
Sqlite as a backing datastore

### ISSUE THREAD

**Issue by Immortalin** [JacobEvelyn/friends#210]
Regex is brittle....

**Comment by Immortalin** [comment]
And potentially suffer from injection/malformed input depending on what you type in

**Comment by JacobEvelyn** [comment]
Hey @Immortalin, thanks for the suggestion, and sorry for the delay! Could you tell me a little more about what you're hoping to accomplish? Is it that you want to `INSERT` via SQL instead of `friends add`? Or something else?

**Comment by JacobEvelyn** [comment]
I haven't heard back, so I'm closing this. Feel free to reopen if you want to chat more about this!
