### ISSUE TITLE
When specifiyng a file that does not exist, prompt to create it instead of aborting

### ISSUE THREAD

**Issue by MartyLake** [JacobEvelyn/friends#214]
Hello,
just installed friends, it looks so promising ! I suggest that when specifiyng a file that does not exist, prompt to create it instead of aborting. This would help installing friends faster :)

**Comment by JacobEvelyn** [comment]
Thanks for the suggestion, @MartyLake! Great idea. I'll see if I can add this today 😄

**Comment by JacobEvelyn** [comment]
@MartyLake looking a little more closely at the code, I'm not sure I totally understand. Right now (on my machine at least), if I run `friends` for the first time and don't have a file, it'll create one. This is true whether you specify a custom name like:

```bash
friends --filename ~/Dropbox/friends.md add activity
```

or if you just use the default (`./friends.md`):

```bash
friends add activity
```

Are you saying:

1. You want `friends` to **_tell_** you when it's creating a new file?
2. You want `friends` to **_ask_** you before creating a new file?
3. You're seeing different behavior, and `friends` errors out when the file doesn't exist on your computer?
    - If this is the case, would you mind running the command with the `--debug` flag (`friends --debug ...`) and pasting the error output here?

**Comment by MartyLake** [comment]
Well, I observed 3, but I'm not able to reproduce it right now. :( sorry for the noise !

**Comment by JacobEvelyn** [comment]
No problem, @MartyLake! If you can reproduce it again please let me know! (Perhaps you were on a read-only file system, or something like that?)

**Comment by MartyLake** [comment]
Will do ;)

Le 16 nov. 2018 14:42, "Jacob Evelyn" <notifications@github.com> a écrit :

No problem, @MartyLake <https://github.com/MartyLake>! If you can reproduce
it again please let me know! (Perhaps you were on a read-only file system,
or something like that?)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/JacobEvelyn/friends/issues/214#issuecomment-439396234>,
or mute the thread
