### ISSUE TITLE
Add new list command to log any activity or note related to specified friend

### ISSUE THREAD

**Issue by MartyLake** [JacobEvelyn/friends#270]
Hello,
I am starting to dig `friends`, thanks for creating such tools :)

I wish I could `friend recall my_friend_s_nick` that would list any activity and note related to the friend.

Sure I can already `edit` the file and grep the name, but I am afraid that if the list grows a bit, friends with same name collide, whereas a nickname rarely collide at all.

This idea come from `ledger reg` that just outputs "what happened" in chronological order, with further filtering only after.

Best,

**Comment by JacobEvelyn** [comment]
Thanks for the kind words, @MartyLake! And thanks for the suggestion. ❤️ 

Are you aware that you can use the `--with` flag on [`friends list activities`](https://github.com/JacobEvelyn/friends#list-activities) and [`friends list notes`](https://github.com/JacobEvelyn/friends#list-notes)? Does that get you what you're looking for?

Or is it important that this new command combine both activities and notes together? If so, could you share more about your use case? Thanks!

**Comment by MartyLake** [comment]
Hello @JacobEvelyn  !

The hardest part of using your tool so far is sticking to journaling.

re new command:

I have decided to clearly separate `activities` for real world interaction, and `notes` for additional info that may or may not originate from activities (birthdate, place of living, new dog).
I have the feeling that if I use the tool a lot, information about one friend will be scattered around multiple activities and note, and I wonder if I could just get an chronological list of activities and notes related on just one friend.

Maybe this need will never materialize though.

Is it a bit clearer like this ? :)

**Comment by JacobEvelyn** [comment]
Hey @MartyLake ! Thanks for the explanation.

It's definitely possible to add a new `list` command that combines `activities` and `notes` in its output. Internally this codebase uses the word "event" to refer to both activities and notes, so this could be `list events`. I'm open to other names though!

Would you be interested in writing a PR for this feature?

**Comment by MartyLake** [comment]
Hello Jacob,

After a while, I realize that I don't use my computer enough for this tool to be reliable for me.
Also, I have no experience in Ruby programming.

In all honesty, I will just close this feature request.
Thanks for taking the time to read and answer my messages, and all the best !
