### ISSUE TITLE
Support Ruby 1.9?

### ISSUE THREAD

**Issue by niklasfi** [JacobEvelyn/friends#39]
Hi, it seems, you're missing an `# encoding: utf-8` somewhere:

    /usr/local/bin/friends:23:in `load': /var/lib/gems/1.9.1/gems/friends-0.5/bin/friends:151: invalid multibyte char (US-ASCII) (SyntaxError)
    /var/lib/gems/1.9.1/gems/friends-0.5/bin/friends:151: invalid multibyte char (US-ASCII)
    /var/lib/gems/1.9.1/gems/friends-0.5/bin/friends:151: syntax error, unexpected $end, expecting ']'
      puts colors.take(count).map { |rgb| Paint["█", rgb] }.join
                                                   ^
        from /usr/local/bin/friends:23:in `<main>'

**Comment by JacobEvelyn** [comment]
Thanks so much for flagging this! I hadn't noticed this because the magic comments aren't necessary  in later versions of Ruby (I think) that I've been using for development. I'll see what I can do about making this codebase work on older versions of Ruby (I believe this and named parameters are the only issues).

In the meantime, if you run with a later version of Ruby it should work fine for you.

**Comment by JacobEvelyn** [comment]
So it looks like based on this and the named parameters I'm using, the code as-is only works with Ruby 2.1+. I'll think about whether I think the benefits of porting this to older versions of Ruby are worth the code muddying (and I'm definitely open to being persuaded that they are).

In the meantime, would it be possible for you to upgrade your version of Ruby to 2.1 (or have multiple versions installed on the same system)?

**Comment by niklasfi** [comment]
It appears, there is no 2.1 package for my distro (ubuntu lts). I only have 2.0, so 1.9 support (or even 2.0) would be great.

**Comment by JacobEvelyn** [comment]
Would this work for you? http://stackoverflow.com/a/33064386/1103543

I'd rather not backport this code to older versions of Ruby without a lot of interest.

**Comment by niklasfi** [comment]
@JacobEvelyn thank you for your help. I guess I'll just wait three months until the new LTE comes out… looking forward to it though :)

**Comment by JacobEvelyn** [comment]
Sorry to hear that @niklasfi. I'll let you know if this changes but as of now I don't have plans to support older versions. I know that's frustrating, and I apologize! :cry:
