### ISSUE TITLE
Reference friends by real name or nickname

### ISSUE THREAD

**Issue by changecase** [JacobEvelyn/friends#40]
Adding an activity with The Dude should be captured as an activity with Jeffrey Lebowski.

```
$ friends add activity "Went bowling with The Dude and Walter."
Activity added: "2015-01-04: Went bowling with Jeffrey Lebowski and Walter Sobchak."
```

Reporting on activities with a friend should work if you use their nickname.

```
$ friends list activities --with "The Dude"
2015-01-04: Went bowling with Jeffrey Lebowski and Walter Sobchak.
```

**Comment by JacobEvelyn** [comment]
Thanks for the suggestion! This has been in my backlog for a while now but I've been unable to land on the specifics of how best to store nicknames internally and add/remove them from friends.

I'm leaning towards something like this:

```markdown
### Friends:
- Jeffrey "The Dude" Lebowski
```

or this:

```markdown
### Friends:
- Jeffrey Lebowski (The Dude, Jeff)
```

The first one feels a little bit more natural (as it's not uncommon to see nicknames written that way), but the second does allow for multiple nicknames, which may be nice or totally unnecessary. I'd love to hear your thoughts!

**Comment by changecase** [comment]
My thoughts were along the second form. You are right though, the first form is way more natural.

Maybe something like this?

```markdown
### Friends:
- Jeffrey Lebowski (aka, "The Dude", "Jeff")
```

It uses a lot more characters, but returns some of the natural feel.

**Comment by JacobEvelyn** [comment]
I like that! I'll see if I can get a basic nickname system working in the next day or so.

**Comment by changecase** [comment]
Awesome. Thanks!

**Comment by fire** [comment]
Can you rename friends (to add nicknames for instance?)?

**Comment by changecase** [comment]
That sounds great! Maybe a separate issue?

**Comment by JacobEvelyn** [comment]
Since some people (like myself) already have friends added I think it's probably easier to start with nicknames only being added, actually. That might be easier than having to remember how to specify a nickname when adding a friend initially, getting the syntax wrong, and ending up with the nickname being treated as part of the formal name.

Would love to hear thoughts here!

**Comment by changecase** [comment]
That sounds great. Then, if you later allow for assigning nicknames at friend creation, you'll probably be able to make use of both parts.

**Comment by JacobEvelyn** [comment]
Exactly!
