### ISSUE TITLE
Integrate with cron for regular reminders

### ISSUE THREAD

**Issue by JacobEvelyn** [JacobEvelyn/friends#56]
I'm a little hazy on what this would actually look like, but I think in its most basic form it would probably be two commands for adding/removing `friends suggest` from your `crontab` (all from within the `friends` program).

**Comment by natejlong** [comment]
This would be super useful; how were you thinking the reminders should be displayed? Desktop notifications, popping up new terminals, emails?

**Comment by JacobEvelyn** [comment]
I'm very open to suggestions, @natejlong! What would you find most helpful?

Also, short of sending an HTTP request to a server, are there easy ways you can think of to make this cross-platform without a long-running Ruby process? Or maybe a long-running Ruby process isn't so bad?

**Comment by natejlong** [comment]
Personally, I would find email notifications to be the best option, and this has the added benefit of hooking right into how cron already sends notifications.

What do you mean by cross-platform?

I would prefer having it pass off all of the long-running scheduling work to cron, but looking around at the gems that fit the bill ([whenever](https://github.com/javan/whenever)) it seems like that still requires the user to set up the actual crontab manually (or almost manually). I don't know any way to set up something with cron invisibly from within the Ruby code, do you?

**Comment by JacobEvelyn** [comment]
Sorry for the slow response. So I've actually played a bit with `whenever` in the past and from what I remember I think it could work with some hackery. I agree that `cron` is nice as an alternative to a long-running Ruby process, but by cross-platform I meant "runs on Windows." I don't want to throw users under the bus because they don't have `cron`, though maybe that's a concern for later on down the road.

**Comment by natejlong** [comment]
Ah okay, yeah that makes sense. At this point I think the best way to solve it is by including documentation of how to set it up as a cron job and leaving the code untouched. From looking at ```whenever```, it seems like all it does is write to the crontab automatically. For a job as simple as this, it might be enough to just include instructions on how to set it up with cron completely manually and independently. I'll try setting it up myself and see how feasible that really is.

This way, at least the code doesn't favor one system or another. Windows users can submit their own best method for scheduling it too (perhaps using [at](https://technet.microsoft.com/en-us/library/bb726974.aspx) or [schtasks](https://technet.microsoft.com/en-us/library/cc725744.aspx)) and if a more seamless, universal solution emerges later on it's just as simple to patch in then as it would be now.

**Comment by JacobEvelyn** [comment]
Okay, I'll keep playing around with this. Thanks for the input! (And input from others is still very much welcome!)

**Comment by natejlong** [comment]
@JacobEvelyn, I played around with setting up cron reminders, but decided not to pursue it further. Setting up automatic emails required setting up postfix or some other email server, and I didn't want to go down that rabbit hole. I also didn't like the UX of a random terminal or notification popping up at regular intervals.

I use Emacs' Org-mode to manage my todos, so I decided to just track reminders there instead. That seems to be a more natural location for friends' reminders and metadata (contact info, birthday, etc.) for now. Let me know if you have any other ideas for this feature though! This is just my personal use case, and I am interested in hearing other ideas.

**Comment by JacobEvelyn** [comment]
Rather than build this in directly, I decided to (for the time being at least) simply encourage users to use other tools like `cron` on their own. See the new README section on [Setting reminders](https://github.com/JacobEvelyn/friends#setting-reminders) for more info.

I'm open to opening this back up if others think there's some functionality here that's worth building into `friends` directly.
