### ISSUE TITLE
Allow dates in natural-language formats

### ISSUE THREAD

**Issue by JacobEvelyn** [JacobEvelyn/friends#65]
Instead of `YYYY-MM-DD`, users should be able to use phrases like "yesterday" or "two Tuesdays ago," as in `git`.

Likely the best way to incorporate this functionality: https://github.com/mojombo/chronic/

**Comment by natejlong** [comment]
I can do this, should be a good task to start with!

**Comment by JacobEvelyn** [comment]
Perfect, thanks so much! Let me know if you need any help!

**Comment by JacobEvelyn** [comment]
@natejlong sorry if you were still working on this, but it had been a while and I wanted to get the feature out the door so I went ahead and implemented it. Let me know if you have any questions, and I hope you can contribute in the future!

**Comment by natejlong** [comment]
Hey @JacobEvelyn , sorry about that; other work has been taking up my time. I will absolutely contribute in the future, I was actually planning my own similar system when I happened to come across yours. Thanks for your work!
