### ISSUE TITLE
Add location data to friends

### ISSUE THREAD

**Issue by JacobEvelyn** [JacobEvelyn/friends#66]
There are a lot of ways this could be incorporated:

- Optionally add a location to each friend
- Optionally add a location to each activity
- Automatically add a location to each activity (using the `geocoder` gem)
- Allow `suggest` and `list friends` and `list activities` filters by location

Would love to hear thoughts on what people would find useful.

**Comment by natejlong** [comment]
Having a location tied to each friend would be useful, but I think tying a location to each activity would be less so. Tracking friends' locations has the obvious use case of letting you filter by location, but I don't see any similar case for the activities. Maybe I'm just coming at this from a different perspective, what did you have in mind?

**Comment by JacobEvelyn** [comment]
I didn't think too deeply about these use cases, but for the activity locations I was thinking about answering the question "What did I do on my trip to Ontario?" The answer being: `friends list activities --in Ontario`

**Comment by andypearson** [comment]
I've started recording activities like:

    Drinking Grog in The Scumm Bar with Guybrush and Elaine

Locations could be implemented just like friends, below is an example `friends.md`

    ### Activities:
    2016-02-15: Drinking Grog on __Melee Island__ with **Guybrush Threepwood** and **Elaine Marley**

    ### Friends:
    - Elaine Marley
    - Guybrush Threepwood (a.k.a Flybrunch)

    ### Locations:
    - The Scumm Bar

You could give a location a full address:

    ### Locations:
    - The Scumm Bar: 14 Melee Island, M0N K3Y

You could also give a friend a location:

    ### Friends:
    - Elaine Marley [The Scumm Bar]

You could then add `--in` as a globally supported flag to filter any list by a specific location.

Eventually each location could have a (cached) latitude and longitude:

    ### Locations:
    - The Scumm Bar: 14 Melee Island, M0N K3Y (51.426614, -0.285645)

And then you could add a `--near` flag, to find friends and activities that are close to a specific address/location.

Thoughts?

**Comment by JacobEvelyn** [comment]
@andypearson Your proposal looks a lot like what I've been thinking about (though I've had fewer Monkey Island references in my thoughts :wink: ). I'm not totally sure I buy the need for lat/long coordinates, especially if something like [`geocoder`](http://www.rubygeocoder.com) could do lookups when needed, but I think we'll get a sense for that as the features are built out and used (e.g. is it more annoying to have adding a location be slow or have `--near` commands be slow, etc.).

In the meantime, I think I'm *almost* comfortable moving forward with the following steps:

1. Add backwards-compatible `### Locations:` heading to `friends.md` file.
2. Add basic `add location` command.
3. Add location matching to activity descriptions (my not-thought-through-at-all vote would be for single underscores: `_The Eiffel Tower_`).
4. Add command to add locations (allow multiple?) to friends.
5. Add `--in` flag to `list` commands.
6. Consider adding a flag you can pass in to automatically choose the closest location from your list and insert it into the activity. (e.g. `Drinking grog with Guybrush` would be recorded as something like `2016-03-15: Drinking grog with **Guybrush Threepwood** [The Scumm Bar]` or `[The Scumm Bar] 2016-03-15: Drinking grog with **Guybrush Threepwood`)
7. Consider adding geocoding to support a `--near` command.

My only hesitation is due to the fact that number 6 in that list is making me wonder if locations should be made into more of a first-class part of recording activities the way dates are (like the second example in item 6). My instinct is they should not because:

- it forces users into recording more information and makes using the program more heavyweight
- it feels less elegant given the fact that previous activities had no locations
- it potentially reduces the flexibility in allowing users to add multiple locations to an activity (though I suppose that isn't a guaranteed result)
- there are privacy concerns with geocoding (minor point since that component is very much just an idea and not definite)

Thoughts @andypearson @natejlong?

**Comment by natejlong** [comment]
I like the idea of treating locations like friends. That seems very lightweight and flexible, and I agree with your concerns about locations being too "heavy", @JacobEvelyn.

The only issue I have is that treating locations as unique entities is a bit simplistic. If I record ```got coffee with Paul Revere at Fanuel Hall```, it would be nice if that activity showed up when searching for activites ```--in Boston```, even though ```Boston``` could be recorded as a separate location distinct from Fanuel Hall. We could use the full address that @andypearson mentioned, searching that for ```Boston```, I suppose. We could also allow nested locations (to some max depth), but that might get messy. What do you all think?

**Comment by JacobEvelyn** [comment]
That's an interesting idea @natejlong but I worry it's adding a lot of complexity when treating locations as unique entities might be good enough for 99% of the use cases. The nesting structure you describe could also be added later if need be so I hesitate to add it now.

**Comment by andypearson** [comment]
This all sounds good!

I think `--in Boston` might just be `--near Boston` with a tighter search radius, but as they are locations I think dealing with them using distance comparison is the way to go.

I've been thinking about how tagging (hashtags, in particular) could also work, so maybe you could add `Fanuel Hall #boston` and then you can `--tagged boston` but this is a big aside!

I'd be keen to cache lat/lng when possible, it'll save geocoding requests.

With regards to Point 6, we could consider a `~/.friends` config file so users can have a specific setup, but for now it's waaaay too much. Points 1-5 get us 90% of the basic useful functionality.

**Comment by JacobEvelyn** [comment]
@andypearson great suggestion on hashtags; I've made #89 for that enhancement.

I agree that points 1-5 get us 90% of the way there and would be good (and fairly simple) to do regardless of what happens on the geocoding front.

**Comment by andypearson** [comment]
Yup, sounds good to me!

**Comment by JacobEvelyn** [comment]
Cool. I've implemented what should be the trickiest parts of this (numbers 1-3) and will tackle the rest either later this weekend or early next week. I've gone ahead and made issues for the remaining components.

**Comment by andypearson** [comment]
Awesome!

**Comment by JacobEvelyn** [comment]
Okay, the rest of this (minus any geocoding fanciness) is implemented and I've released v0.17. @andypearson @natejlong would love to hear what you guys think!

**Comment by andypearson** [comment]
Awesome! I've extracted all of my locations as proper things and the highlighting is working great. I'll let you know how I get on with it!

It'd be cool to `graph` locations, and also see favourite locations (adding a new favourite command makes sense). I'd be up for picking these up next, unless there's something else you'd like me to look at?

**Comment by JacobEvelyn** [comment]
Listing favorite locations makes a lot of sense; I've just created #108 for that. By `graph`ing locations I'm assuming you mean with output similar to the existing graph? If so I made #109. In the long run it would be neat to think about an ASCII-rendered map, but that feels a little overboard for now. :)

**Comment by JacobEvelyn** [comment]
Closing this issue, since the ideas from it have been turned into other issues.
