### ISSUE TITLE
Add change name command

### ISSUE THREAD

**Issue by JacobEvelyn** [JacobEvelyn/friends#68]
Should be pretty straightforward.

**Comment by bloomyminded** [comment]
I'd like to tackle this one

**Comment by JacobEvelyn** [comment]
Perfect! Let me know if you need any guidance.

**Comment by bloomyminded** [comment]
Thanks jacob, will do.

**Comment by bloomyminded** [comment]
I'm having an error with Rubocop on several lines I haven't touched. Suggestions?

**Comment by JacobEvelyn** [comment]
Ah sorry I didn't see this in time. Glad you figured it out, and let me know if any other issues crop up.

**Comment by JacobEvelyn** [comment]
Done with #75.
