### ISSUE TITLE
All command-line arguments should result in prompts if not supplied

### ISSUE THREAD

**Issue by JacobEvelyn** [JacobEvelyn/friends#69]
It would be nice to allow this, similar to how activity descriptions can be entered via prompt, but for all commands. So I could just say `friends graph`.

**Comment by andypearson** [comment]
I'd be interested in digging in to this a little bit as I've been using `friends` quite a lot recently.

One thing I'm wondering, in the case of things like `graph` it could default to generating a graph of all your activities, which is then "filtered" by passing in the first argument.

**Comment by JacobEvelyn** [comment]
Ah, that's an interesting use case of `graph` that I hadn't thought of, and it kind of throws a wrench in this feature since `friends graph` was one of the main motivations (though `friends add friend` is still another where it would be useful).

I just made #83 (which it sounds like you may be interested in working on?) to address your `graph` suggestion—it's yours if you want it!

I'm also interested in hearing your thoughts on this issue (assuming #83 happens) and #84, which is somewhat related.

**Comment by andypearson** [comment]
I'm up for making #83 my first PR :)

I haven't had a review of all commands, but I was wondering if it's possible to adopt a common pattern where all "read" commands have a sensible "unfiltered" result, which you can then refine using additional arguments and all "write" commands provide an interactive way of completing the full command.

**Comment by JacobEvelyn** [comment]
I think both of those ideas make sense; the latter is really what I was getting at with this issue originally.

**Comment by JacobEvelyn** [comment]
Closing this for now, as it seems this Issue has transformed a bit, and other Issues that have spawned from it can be completed independently.
