### ISSUE TITLE
4 RuboCop errors prevent git commit

### ISSUE THREAD

**Issue by bloomyminded** [JacobEvelyn/friends#78]
Current master has four RuboCop errors that prevent a git commit without skipping.  These are not of great importance but I feel the change is beneficial if not for style then at least to prevent confusion while contributing.

**Comment by JacobEvelyn** [comment]
Thanks for doing this! My Overcommit/Rubocop setup has been a bit broken recently because of https://github.com/brigade/overcommit/issues/315, so I've sadly gotten used to skipping validations.

I really appreciate this change though!

**Comment by bloomyminded** [comment]
No problem.  I had never used RuboCop or overcommit before so it was a bit confusing.  Apparently it only prevents a commit if one of the files has an error.  This is why running rubocop in the directory produced far more offenses.

**Comment by JacobEvelyn** [comment]
Fixed in #79.
