### ISSUE TITLE
Treat double names as a single name

### ISSUE THREAD

**Issue by niklasfi** [JacobEvelyn/friends#80]
In Germany, it is quite common to have double names (e.g. first names consisting of two first names). Unfortunately, their use currently leads to garbled output. Here is an example:

    friends add friend "Anna-Lena Mustermann"
    friends add friend "Lena Test"
    friends add activity "went fishing with Anna-Lena"

that last command outputs

    Activity added: "2016-01-20: went fishing with Anna-Lena Test Mustermann"

when one would expect something similar to

    Activity added: "2016-01-20: went fishing with Anna-Lena Mustermann"

Note the recursive replacement: `Anna-Lena` turned into `Anna-**Lena Test**` which turned into `**Anna-**Lena Test** Mustermann**` in the `friends.md` database.

This certainly isn't what the user intends. I would suggest to treat en-dashes/minus signs as regular characters which don't indicate a splitting boundary.

p.s.: finally got it working :)

**Comment by JacobEvelyn** [comment]
Hey @niklasfi, glad you got it working! Thanks for the bug report; you're right that this is a problem and not at all what's intended. The slight problem is that at least in my own experience it's not uncommon for names to have en dashes/minus signs next to them in normal writing. (As one example, I've seen lots of people use two en dashes, `--`, to serve as an em dash, particularly with monospaced fonts as in most shell environments.)

I'll think about how best to handle this (maybe longer regexes should always be checked before shorter ones?) and have a fix out as soon as I can (probably in about 24 hours—it would be shorter but this week is somewhat crazy for me at work).

Thanks for spotting this!

**Comment by JacobEvelyn** [comment]
This ended up being trickier than I thought, but kind of fun to puzzle through as well. :smiley:

**Comment by JacobEvelyn** [comment]
This is fixed in version `0.13`, which I just released to RubyGems. Get it with `friends update` and you should be good to go!
