### ISSUE TITLE
Allow `graph` without arguments to graph all activities

### ISSUE THREAD

**Issue by JacobEvelyn** [JacobEvelyn/friends#83]

**Comment by andypearson** [comment]
I'll take this!

**Comment by JacobEvelyn** [comment]
Perfect, thanks! Let me know if you have questions or if I can help in any way!

**Comment by andypearson** [comment]
I'm not sure if it's possible to make the PR appear here, but, I've done one!

**Comment by JacobEvelyn** [comment]
Yep I see the link from here, thanks!

**Comment by JacobEvelyn** [comment]
I've just released this in version 0.16.

**Comment by andypearson** [comment]
Awesome! Cheers @JacobEvelyn!
