### ISSUE TITLE
Should the "more than one friend found" errors be replaced by a best guess?

### ISSUE THREAD

**Issue by JacobEvelyn** [JacobEvelyn/friends#84]
When I type `friends list activities --with John` or `friends graph John` it's annoying to get this error:

```
Error: More than one friend found for "John": John Deere, John Doe
```

It might be nicer if `friends` automatically picked the friend with more activities in these cases, but I can see arguments in favor of keeping the current system as-is as well. I think I'm leaning towards this idea because much of the philosophy of `friends` is to let the program simplify and make assumptions for you (as in friend matching in activities).

Curious what others think here.

**Comment by andypearson** [comment]
This could be solved with a second "suggestion" step:

    $ friends list activities --with John

    Which John?
    1. John Deere
    2. John Doe

    >

**Comment by JacobEvelyn** [comment]
I've thought about that as well. It seems nice on the surface but I don't love the fact that it differs from the auto-matching paradigm of adding activities and yet isn't much easier than writing a friend's full name out. I go back and forth though and could probably be convinced in either direction.

**Comment by andypearson** [comment]
I'm not sure I have a solid case in either direction!

Interestingly, I added an activity the other day and expected "David B" to find me the correct David but it found the wrong David and I ended up with an extra "B" in my activity.

This doesn't help in your particular example, but in most cases it'd greatly increase the chance of finding a unique name.

**Comment by JacobEvelyn** [comment]
That's a great use case. I just created #87 for implementing that (and would love your thoughts on the open questions I posed in that issue).

**Comment by andypearson** [comment]
The other way of getting around this would be to encourage the user to create a nickname for one of the Johns.

**Comment by JacobEvelyn** [comment]
For the time being I'm going to keep the "More than one friend found" error as-is. As I mentioned above, it's pretty simple for the user to correct, and it keeps the code straightforward.

I'm willing to re-open this Issue though if others find this to be a pain point.
