### ISSUE TITLE
Using bin/friends during development

### ISSUE THREAD

**Issue by andypearson** [JacobEvelyn/friends#86]
Whilst working on #83 I discovered running `bin/friends` refers to the version of the gem that you have installed rather than the one within the repository.

I changed:

    require "friends/introvert"
    require "friends/version"

To:

    require_relative "../lib/friends/introvert"
    require_relative "../lib/friends/version"

And that seems to do the trick.

It makes sense to me that it would work this way in development, though I haven't tried to figure out if this will work when the gem is installed.

Is there a different way to run `bin/friends` during development that works as I would expect?

**Comment by JacobEvelyn** [comment]
I haven't had this problem when using `bundle exec bin/friends` for local development. Have you tried that? If that works for you I'll note that in the `CONTRIBUTING.md` file.

**Comment by andypearson** [comment]
Whoops! `bundle exec bin/friends` works great, sorry for the false alarm!

**Comment by JacobEvelyn** [comment]
Good to hear! Just added https://github.com/JacobEvelyn/friends/commit/bb58eb8b8af647591cdd640de65334177bc4bbef?short_path=6a33714#diff-6a3371457528722a734f3c51d9238c13 to clarify this a bit.

**Comment by andypearson** [comment]
Nice!
