### ISSUE TITLE
Allow friends to be found with first name and last name initial

### ISSUE THREAD

**Issue by JacobEvelyn** [JacobEvelyn/friends#87]
"Earnest H" should correctly be turned into `**Earnest Hemingway**` instead of `**Earnest Hemingway** H` or `**Earnest Shackleton** H`.

**Open question 1**: is there an elegant way to handle periods (e.g. "Earnest H. and I went to the store" and "I went to the store with Earnest H. We both love shopping.")? Off the cuff it might be easy enough to include the period in the "name" if it's followed by some amount of whitespace and then a lowercase letter (for instance with a lookahead regex), but there could be other good edge cases to consider here.

**Open question 2**: should this concern itself with more complex names (like "James Earl Jones" or "Jennifer Love-Hewitt")? Are there simple rules that will handle most of those cases?

**Comment by andypearson** [comment]
1. I'm not keen on having to rely on precise capitalisation to work out whether the period should or shouldn't be included, but I also don't like the idea of a non-natural syntax like `Earnest[H]`. We might have to start playing to see what kinds of edge cases emerge.

2. I'm not even sure how both of those examples would be naturally initialised to begin with!

**Comment by JacobEvelyn** [comment]
I just added this functionality (using the capitalization scheme I detailed above) in version 0.18. I'm very interested to hear how it works for you!

**Comment by andypearson** [comment]
I didn't notice that this went in! I'll give it a try next time I'm entering possibly ambiguous names.

**Comment by JacobEvelyn** [comment]
Awesome, thanks! Would love to hear what you think.
