### ISSUE TITLE
Filter activities based on more than one friend/tag/etc.

### ISSUE THREAD

**Issue by JacobEvelyn** [JacobEvelyn/friends#88]
It could be nice to be able to filter activities like so: `friends list activites --with Jessie --with James` (or some other syntax). This should possibly also be allowed for locations (#66) or tags (#89).

**Open question**: should multiple flags return the _union_ of activities that match or the _intersection_?

**Comment by andypearson** [comment]
I'd say it should be an intersection by default, it just feels like you'd be trying to make your filtering more specific. Maybe there should be a way of switching to union as well though with an additional flag?

Comma separated could also work as a syntax:

    friends list activites --with "Jessie, James"
    friends list activites --with-any "Jessie, James"

**Comment by JacobEvelyn** [comment]
Yeah I buy that. So the PR here would be to add multiple `--with` tags (I prefer this syntax, so long as GLI doesn't make it hard) for an intersection search and an optional `--any` tag to switch to a union search.

**Comment by andypearson** [comment]
Sounds good to me!

**Comment by JacobEvelyn** [comment]
As specified above, this feature depends somewhat on this feature request I've made to GLI: https://github.com/davetron5000/gli/issues/240

I may make a pull request to GLI myself if I have time.

**Comment by JacobEvelyn** [comment]
This is available in v0.30.
