### ISSUE TITLE
Add hashtag capabilities to activities

### ISSUE THREAD

**Issue by JacobEvelyn** [JacobEvelyn/friends#89]
It would be nice to be able to do something like this:

`friends add activity "Went for a run. #exercise"`

and then later filter activities like:

`friends list activities --tagged exercise`

or

`friends list activities --with James --tagged restaurants`

For now this would only support one tag to be passed to the `--tagged` argument (see #88 for more details on lifting that limitation).

**Comment by andypearson** [comment]
I'd like to be able to tag friends as well, so I can search for people that I worked with, or people I know from school.

**Comment by JacobEvelyn** [comment]
Ah interesting, so you're saying there might be friends under the `#work` tag as well as activities under the `#work` tag. That makes sense to me. I just created #90 for this; let me know if that looks like what you were thinking.
