### ISSUE TITLE
Add hashtag capabilities to friends

### ISSUE THREAD

**Issue by JacobEvelyn** [JacobEvelyn/friends#90]
So a friend could be a `#work` friend or a `#family` friend, and they could be combined like:

```
friends.md

### Friends:
- Grace Hopper (a.k.a. The Admiral) #work #school
- Marie Curie #school
```

@andypearson is this what you were thinking?

**Comment by andypearson** [comment]
Yup, this is exactly what I was imagining!

**Comment by andypearson** [comment]
Super excited for this feature! Thanks for adding it :D

**Comment by JacobEvelyn** [comment]
I'd love to hear how it works for you!
