### ISSUE TITLE
Have a way to correct mistakes?

### ISSUE THREAD

**Issue by JacobEvelyn** [JacobEvelyn/friends#91]
Though `friends` generally gets things right (and issues like #87 will improve that), sometimes it picks the wrong friend, or thinks you're talking about a friend when you're really talking about "Joe's Diner." It might be helpful to be able to edit activities through `friends` to correct mistakes like these.

Some possibilities include:

- `friends undo`
  - Undo the most recent `add activity` (or `add friend`?) command.
  - Weird semantics (what's expected for two consecutive `friends undo` commands?).
  - Requires polluting the `friends.md` file with an indicator of the most recently added friend/activity.
- `friends delete activity <date>`
  - Prompts the user to select the activity to delete.
  - Simple; don't have to deal with edits.
- `friends edit activity <date>`
  - Prompts the user to select the activity to edit.
  - An edit interface might be nicer?
- Something else?

**Comment by natejlong** [comment]
I know this is kind of a non-solution, but adding a `friends edit` which just opens the friends file in `$EDITOR` may be the best way to deal with this. I think the simplicity of the friends.md structure that you designed makes this acceptable, and avoids having to get bogged down in turning `friends` from a markdown file into a pseudo-database. I find myself often making quick fixes or bulk edits with `vim $FRIENDS` (I've defined that to point to my file) and I think it's a fine experience.

[Ledger](https://github.com/ledger/ledger) is a nice example of this relationship working in a mature project. It has a command-line reporting interface, but fully expects you to provide your own editor and accepts this as being a key part of the user experience.

What do you think?

**Comment by JacobEvelyn** [comment]
Interesting; that's a neat approach that I hadn't thought of before. At the very least it could serve as a solution for the time being and if the need for more specialized commands arises those could be added as well. I like this!

**Comment by JacobEvelyn** [comment]
So to be clear, this change will now be to just add a `friends edit` command which opens the friends file in `$EDITOR` (falling back to `vim` if undefined, as is typical). Up for whoever wants to take it!

**Comment by JacobEvelyn** [comment]
This has been added in version 0.18.
